//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class ApplyForce : Message
    {
        public const string RosMessageName = "niryo_moveit/ApplyForce";

        public double acceleration;
        public double steering_angle;
        public int cmd_id;
        public int num_obstacles;

        public ApplyForce()
        {
            this.acceleration = 0.0;
            this.steering_angle = 0.0;
            this.cmd_id = 0;
            this.num_obstacles = 0;
        }

        public ApplyForce(double acceleration, double steering_angle, int cmd_id, int num_obstacles)
        {
            this.acceleration = acceleration;
            this.steering_angle = steering_angle;
            this.cmd_id = cmd_id;
            this.num_obstacles = num_obstacles;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.acceleration));
            listOfSerializations.Add(BitConverter.GetBytes(this.steering_angle));
            listOfSerializations.Add(BitConverter.GetBytes(this.cmd_id));
            listOfSerializations.Add(BitConverter.GetBytes(this.num_obstacles));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.acceleration = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.steering_angle = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.cmd_id = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.num_obstacles = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "ApplyForce: " +
            "\nacceleration: " + acceleration.ToString() +
            "\nsteering_angle: " + steering_angle.ToString() +
            "\ncmd_id: " + cmd_id.ToString() +
            "\nnum_obstacles: " + num_obstacles.ToString();
        }
    }
}
