//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class Camera : Message
    {
        public const string RosMessageName = "niryo_moveit/Camera";

        public Sensor.Image frame;

        public Camera()
        {
            this.frame = new Sensor.Image();
        }

        public Camera(Sensor.Image frame)
        {
            this.frame = frame;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(frame.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.frame.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "Camera: " +
            "\nframe: " + frame.ToString();
        }
    }
}
