//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class CarSceneData : Message
    {
        public const string RosMessageName = "niryo_moveit/CarSceneData";

        public Sphere car;
        public int last_executed_cmd_id;

        public CarSceneData()
        {
            this.car = new Sphere();
            this.last_executed_cmd_id = 0;
        }

        public CarSceneData(Sphere car, int last_executed_cmd_id)
        {
            this.car = car;
            this.last_executed_cmd_id = last_executed_cmd_id;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(car.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.last_executed_cmd_id));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.car.Deserialize(data, offset);
            this.last_executed_cmd_id = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "CarSceneData: " +
            "\ncar: " + car.ToString() +
            "\nlast_executed_cmd_id: " + last_executed_cmd_id.ToString();
        }
    }
}
