//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class SimCommand : Message
    {
        public const string RosMessageName = "niryo_moveit/SimCommand";

        public int cmd;
        public ApplyForce ApplyForce;

        public SimCommand()
        {
            this.cmd = 0;
            this.ApplyForce = new ApplyForce();
        }

        public SimCommand(int cmd, ApplyForce ApplyForce)
        {
            this.cmd = cmd;
            this.ApplyForce = ApplyForce;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.cmd));
            listOfSerializations.AddRange(ApplyForce.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.cmd = BitConverter.ToInt32(data, offset);
            offset += 4;
            offset = this.ApplyForce.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "SimCommand: " +
            "\ncmd: " + cmd.ToString() +
            "\nApplyForce: " + ApplyForce.ToString();
        }
    }
}
