//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class SimStatus : Message
    {
        public const string RosMessageName = "niryo_moveit/SimStatus";

        public int status;

        public SimStatus()
        {
            this.status = 0;
        }

        public SimStatus(int status)
        {
            this.status = status;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.status));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.status = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "SimStatus: " +
            "\nstatus: " + status.ToString();
        }
    }
}
