//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class Sphere : Message
    {
        public const string RosMessageName = "niryo_moveit/Sphere";

        public double speed;
        public double location_x;
        public double location_y;
        public double location_z;
        public double cost;
        public double dist_from_traj;
        public double dist_from_goal;
        public double rotation_z;
        public double angular_velocity;
        public double acceleration;
        public double left;
        public double forward_left;
        public double forward_left_left;
        public double n_27_50;
        public double n_25_00;
        public double n_22_50;
        public double n_20_00;
        public double n_17_50;
        public double n_15_00;
        public double n_12_50;
        public double n_10_00;
        public double n_07_50;
        public double n_05_00;
        public double n_02_50;
        public double forward;
        public double p_02_50;
        public double p_05_00;
        public double p_07_50;
        public double p_10_00;
        public double p_12_50;
        public double p_15_00;
        public double p_17_50;
        public double p_20_00;
        public double p_22_50;
        public double p_25_00;
        public double p_27_50;
        public double forward_right_right;
        public double forward_right;
        public double right;
        public double goal_1;
        public double goal_2;
        public double goal_3;
        public double goal_4;
        public bool has_reached_goal;
        public bool has_crashed;
        public string last_goal_reached;
        public string current_goal;

        public Sphere()
        {
            this.speed = 0.0;
            this.location_x = 0.0;
            this.location_y = 0.0;
            this.location_z = 0.0;
            this.cost = 0.0;
            this.dist_from_traj = 0.0;
            this.dist_from_goal = 0.0;
            this.rotation_z = 0.0;
            this.angular_velocity = 0.0;
            this.acceleration = 0.0;
            this.left = 0.0;
            this.forward_left = 0.0;
            this.forward_left_left = 0.0;
            this.n_27_50 = 0.0;
            this.n_25_00 = 0.0;
            this.n_22_50 = 0.0;
            this.n_20_00 = 0.0;
            this.n_17_50 = 0.0;
            this.n_15_00 = 0.0;
            this.n_12_50 = 0.0;
            this.n_10_00 = 0.0;
            this.n_07_50 = 0.0;
            this.n_05_00 = 0.0;
            this.n_02_50 = 0.0;
            this.forward = 0.0;
            this.p_02_50 = 0.0;
            this.p_05_00 = 0.0;
            this.p_07_50 = 0.0;
            this.p_10_00 = 0.0;
            this.p_12_50 = 0.0;
            this.p_15_00 = 0.0;
            this.p_17_50 = 0.0;
            this.p_20_00 = 0.0;
            this.p_22_50 = 0.0;
            this.p_25_00 = 0.0;
            this.p_27_50 = 0.0;
            this.forward_right_right = 0.0;
            this.forward_right = 0.0;
            this.right = 0.0;
            this.goal_1 = 0.0;
            this.goal_2 = 0.0;
            this.goal_3 = 0.0;
            this.goal_4 = 0.0;
            this.has_reached_goal = false;
            this.has_crashed = false;
            this.last_goal_reached = "";
            this.current_goal = "";
        }

        public Sphere(double speed, double location_x, double location_y, double location_z, double cost, double dist_from_traj, double dist_from_goal, double rotation_z, double angular_velocity, double acceleration, double left, double forward_left, double forward_left_left, double n_27_50, double n_25_00, double n_22_50, double n_20_00, double n_17_50, double n_15_00, double n_12_50, double n_10_00, double n_07_50, double n_05_00, double n_02_50, double forward, double p_02_50, double p_05_00, double p_07_50, double p_10_00, double p_12_50, double p_15_00, double p_17_50, double p_20_00, double p_22_50, double p_25_00, double p_27_50, double forward_right_right, double forward_right, double right, double goal_1, double goal_2, double goal_3, double goal_4, bool has_reached_goal, bool has_crashed, string last_goal_reached, string current_goal)
        {
            this.speed = speed;
            this.location_x = location_x;
            this.location_y = location_y;
            this.location_z = location_z;
            this.cost = cost;
            this.dist_from_traj = dist_from_traj;
            this.dist_from_goal = dist_from_goal;
            this.rotation_z = rotation_z;
            this.angular_velocity = angular_velocity;
            this.acceleration = acceleration;
            this.left = left;
            this.forward_left = forward_left;
            this.forward_left_left = forward_left_left;
            this.n_27_50 = n_27_50;
            this.n_25_00 = n_25_00;
            this.n_22_50 = n_22_50;
            this.n_20_00 = n_20_00;
            this.n_17_50 = n_17_50;
            this.n_15_00 = n_15_00;
            this.n_12_50 = n_12_50;
            this.n_10_00 = n_10_00;
            this.n_07_50 = n_07_50;
            this.n_05_00 = n_05_00;
            this.n_02_50 = n_02_50;
            this.forward = forward;
            this.p_02_50 = p_02_50;
            this.p_05_00 = p_05_00;
            this.p_07_50 = p_07_50;
            this.p_10_00 = p_10_00;
            this.p_12_50 = p_12_50;
            this.p_15_00 = p_15_00;
            this.p_17_50 = p_17_50;
            this.p_20_00 = p_20_00;
            this.p_22_50 = p_22_50;
            this.p_25_00 = p_25_00;
            this.p_27_50 = p_27_50;
            this.forward_right_right = forward_right_right;
            this.forward_right = forward_right;
            this.right = right;
            this.goal_1 = goal_1;
            this.goal_2 = goal_2;
            this.goal_3 = goal_3;
            this.goal_4 = goal_4;
            this.has_reached_goal = has_reached_goal;
            this.has_crashed = has_crashed;
            this.last_goal_reached = last_goal_reached;
            this.current_goal = current_goal;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.speed));
            listOfSerializations.Add(BitConverter.GetBytes(this.location_x));
            listOfSerializations.Add(BitConverter.GetBytes(this.location_y));
            listOfSerializations.Add(BitConverter.GetBytes(this.location_z));
            listOfSerializations.Add(BitConverter.GetBytes(this.cost));
            listOfSerializations.Add(BitConverter.GetBytes(this.dist_from_traj));
            listOfSerializations.Add(BitConverter.GetBytes(this.dist_from_goal));
            listOfSerializations.Add(BitConverter.GetBytes(this.rotation_z));
            listOfSerializations.Add(BitConverter.GetBytes(this.angular_velocity));
            listOfSerializations.Add(BitConverter.GetBytes(this.acceleration));
            listOfSerializations.Add(BitConverter.GetBytes(this.left));
            listOfSerializations.Add(BitConverter.GetBytes(this.forward_left));
            listOfSerializations.Add(BitConverter.GetBytes(this.forward_left_left));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_27_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_25_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_22_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_20_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_17_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_15_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_12_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_10_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_07_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_05_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.n_02_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.forward));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_02_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_05_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_07_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_10_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_12_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_15_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_17_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_20_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_22_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_25_00));
            listOfSerializations.Add(BitConverter.GetBytes(this.p_27_50));
            listOfSerializations.Add(BitConverter.GetBytes(this.forward_right_right));
            listOfSerializations.Add(BitConverter.GetBytes(this.forward_right));
            listOfSerializations.Add(BitConverter.GetBytes(this.right));
            listOfSerializations.Add(BitConverter.GetBytes(this.goal_1));
            listOfSerializations.Add(BitConverter.GetBytes(this.goal_2));
            listOfSerializations.Add(BitConverter.GetBytes(this.goal_3));
            listOfSerializations.Add(BitConverter.GetBytes(this.goal_4));
            listOfSerializations.Add(BitConverter.GetBytes(this.has_reached_goal));
            listOfSerializations.Add(BitConverter.GetBytes(this.has_crashed));
            listOfSerializations.Add(SerializeString(this.last_goal_reached));
            listOfSerializations.Add(SerializeString(this.current_goal));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.speed = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.location_x = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.location_y = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.location_z = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.cost = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.dist_from_traj = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.dist_from_goal = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.rotation_z = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.angular_velocity = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.acceleration = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.left = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.forward_left = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.forward_left_left = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_27_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_25_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_22_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_20_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_17_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_15_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_12_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_10_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_07_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_05_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.n_02_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.forward = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_02_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_05_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_07_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_10_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_12_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_15_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_17_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_20_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_22_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_25_00 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.p_27_50 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.forward_right_right = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.forward_right = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.right = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.goal_1 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.goal_2 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.goal_3 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.goal_4 = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.has_reached_goal = BitConverter.ToBoolean(data, offset);
            offset += 1;
            this.has_crashed = BitConverter.ToBoolean(data, offset);
            offset += 1;
            var last_goal_reachedStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.last_goal_reached = DeserializeString(data, offset, last_goal_reachedStringBytesLength);
            offset += last_goal_reachedStringBytesLength;
            var current_goalStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.current_goal = DeserializeString(data, offset, current_goalStringBytesLength);
            offset += current_goalStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "Sphere: " +
            "\nspeed: " + speed.ToString() +
            "\nlocation_x: " + location_x.ToString() +
            "\nlocation_y: " + location_y.ToString() +
            "\nlocation_z: " + location_z.ToString() +
            "\ncost: " + cost.ToString() +
            "\ndist_from_traj: " + dist_from_traj.ToString() +
            "\ndist_from_goal: " + dist_from_goal.ToString() +
            "\nrotation_z: " + rotation_z.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString() +
            "\nacceleration: " + acceleration.ToString() +
            "\nleft: " + left.ToString() +
            "\nforward_left: " + forward_left.ToString() +
            "\nforward_left_left: " + forward_left_left.ToString() +
            "\nn_27_50: " + n_27_50.ToString() +
            "\nn_25_00: " + n_25_00.ToString() +
            "\nn_22_50: " + n_22_50.ToString() +
            "\nn_20_00: " + n_20_00.ToString() +
            "\nn_17_50: " + n_17_50.ToString() +
            "\nn_15_00: " + n_15_00.ToString() +
            "\nn_12_50: " + n_12_50.ToString() +
            "\nn_10_00: " + n_10_00.ToString() +
            "\nn_07_50: " + n_07_50.ToString() +
            "\nn_05_00: " + n_05_00.ToString() +
            "\nn_02_50: " + n_02_50.ToString() +
            "\nforward: " + forward.ToString() +
            "\np_02_50: " + p_02_50.ToString() +
            "\np_05_00: " + p_05_00.ToString() +
            "\np_07_50: " + p_07_50.ToString() +
            "\np_10_00: " + p_10_00.ToString() +
            "\np_12_50: " + p_12_50.ToString() +
            "\np_15_00: " + p_15_00.ToString() +
            "\np_17_50: " + p_17_50.ToString() +
            "\np_20_00: " + p_20_00.ToString() +
            "\np_22_50: " + p_22_50.ToString() +
            "\np_25_00: " + p_25_00.ToString() +
            "\np_27_50: " + p_27_50.ToString() +
            "\nforward_right_right: " + forward_right_right.ToString() +
            "\nforward_right: " + forward_right.ToString() +
            "\nright: " + right.ToString() +
            "\ngoal_1: " + goal_1.ToString() +
            "\ngoal_2: " + goal_2.ToString() +
            "\ngoal_3: " + goal_3.ToString() +
            "\ngoal_4: " + goal_4.ToString() +
            "\nhas_reached_goal: " + has_reached_goal.ToString() +
            "\nhas_crashed: " + has_crashed.ToString() +
            "\nlast_goal_reached: " + last_goal_reached.ToString() +
            "\ncurrent_goal: " + current_goal.ToString();
        }
    }
}
