//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.Std
{
    // std_msgs/String. Hand-added (the project only generated niryo_moveit
    // types) so the trainer's policy_rollouts topic - a JSON payload shipped
    // as a std_msgs/String - can be subscribed to by TrajectoryRolloutViz.
    // Wire layout matches the standard length-prefixed UTF8 string the base
    // Message.SerializeString / DeserializeString helpers produce (same as
    // the string fields in niryo_moveit/Sphere).
    public class StringMsg : Message
    {
        public const string RosMessageName = "std_msgs/String";

        public string data;

        public StringMsg()
        {
            this.data = "";
        }

        public StringMsg(string data)
        {
            this.data = data;
        }

        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.data));
            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var dataStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.data = DeserializeString(data, offset, dataStringBytesLength);
            offset += dataStringBytesLength;
            return offset;
        }

        public override string ToString()
        {
            return "StringMsg: " +
            "\ndata: " + data.ToString();
        }
    }
}
