//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveExecutorServiceRequest : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveExecutorService";

        public Moveit.RobotTrajectory trajectory;

        public MoveExecutorServiceRequest()
        {
            this.trajectory = new Moveit.RobotTrajectory();
        }

        public MoveExecutorServiceRequest(Moveit.RobotTrajectory trajectory)
        {
            this.trajectory = trajectory;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(trajectory.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.trajectory.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MoveExecutorServiceRequest: " +
            "\ntrajectory: " + trajectory.ToString();
        }
    }
}
