//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class PoseExecutorServiceResponse : Message
    {
        public const string RosMessageName = "niryo_moveit/PoseExecutorService";

        public bool accepted;

        public PoseExecutorServiceResponse()
        {
            this.accepted = false;
        }

        public PoseExecutorServiceResponse(bool accepted)
        {
            this.accepted = accepted;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.accepted));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.accepted = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "PoseExecutorServiceResponse: " +
            "\naccepted: " + accepted.ToString();
        }
    }
}
