//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class ApplyForce : Message
    {
        public const string RosMessageName = "niryo_moveit/ApplyForce";

        public double acceleration;
        public double steering_angle;

        public ApplyForce()
        {
            this.acceleration = 0.0;
            this.steering_angle = 0.0;
        }

        public ApplyForce(double acceleration, double steering_angle)
        {
            this.acceleration = acceleration;
            this.steering_angle = steering_angle;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.acceleration));
            listOfSerializations.Add(BitConverter.GetBytes(this.steering_angle));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.acceleration = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.steering_angle = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "ApplyForce: " +
            "\nacceleration: " + acceleration.ToString() +
            "\nsteering_angle: " + steering_angle.ToString();
        }
    }
}
