//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveCommand : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveCommand";

        public int cmd_type;
        public Moveit.RobotTrajectory trajectory;

        public MoveCommand()
        {
            this.cmd_type = 0;
            this.trajectory = new Moveit.RobotTrajectory();
        }

        public MoveCommand(int cmd_type, Moveit.RobotTrajectory trajectory)
        {
            this.cmd_type = cmd_type;
            this.trajectory = trajectory;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.cmd_type));
            listOfSerializations.AddRange(trajectory.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.cmd_type = BitConverter.ToInt32(data, offset);
            offset += 4;
            offset = this.trajectory.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MoveCommand: " +
            "\ncmd_type: " + cmd_type.ToString() +
            "\ntrajectory: " + trajectory.ToString();
        }
    }
}
