//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class PoleCart : Message
    {
        public const string RosMessageName = "niryo_moveit/PoleCart";

        public double hand_tangent_speed;
        public double pole_hand_angle;
        public double pole_angular_speed;
        public bool upright;

        public PoleCart()
        {
            this.hand_tangent_speed = 0.0;
            this.pole_hand_angle = 0.0;
            this.pole_angular_speed = 0.0;
            this.upright = false;
        }

        public PoleCart(double hand_tangent_speed, double pole_hand_angle, double pole_angular_speed, bool upright)
        {
            this.hand_tangent_speed = hand_tangent_speed;
            this.pole_hand_angle = pole_hand_angle;
            this.pole_angular_speed = pole_angular_speed;
            this.upright = upright;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.hand_tangent_speed));
            listOfSerializations.Add(BitConverter.GetBytes(this.pole_hand_angle));
            listOfSerializations.Add(BitConverter.GetBytes(this.pole_angular_speed));
            listOfSerializations.Add(BitConverter.GetBytes(this.upright));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.hand_tangent_speed = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.pole_hand_angle = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.pole_angular_speed = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.upright = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "PoleCart: " +
            "\nhand_tangent_speed: " + hand_tangent_speed.ToString() +
            "\npole_hand_angle: " + pole_hand_angle.ToString() +
            "\npole_angular_speed: " + pole_angular_speed.ToString() +
            "\nupright: " + upright.ToString();
        }
    }
}
