# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: virtual_endpoint/proto/ros_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='virtual_endpoint/proto/ros_service.proto',
  package='virtual_endpoint',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(virtual_endpoint/proto/ros_service.proto\x12\x10virtual_endpoint\"3\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08msg_type\x18\x02 \x01(\t\"\x1c\n\x0cTopicMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"M\n\x0eServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x14\n\x0cservice_type\x18\x02 \x01(\t\x12\x0f\n\x07request\x18\x04 \x01(\t\"#\n\x0fServiceResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xb0\x01\n\x07RosNode\x12Q\n\tSubscribe\x12\".virtual_endpoint.SubscribeRequest\x1a\x1e.virtual_endpoint.TopicMessage0\x01\x12R\n\x0b\x43\x61llService\x12 .virtual_endpoint.ServiceRequest\x1a!.virtual_endpoint.ServiceResponseb\x06proto3'
)




_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='virtual_endpoint.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='virtual_endpoint.SubscribeRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='virtual_endpoint.SubscribeRequest.msg_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=113,
)


_TOPICMESSAGE = _descriptor.Descriptor(
  name='TopicMessage',
  full_name='virtual_endpoint.TopicMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='virtual_endpoint.TopicMessage.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=143,
)


_SERVICEREQUEST = _descriptor.Descriptor(
  name='ServiceRequest',
  full_name='virtual_endpoint.ServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='virtual_endpoint.ServiceRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_type', full_name='virtual_endpoint.ServiceRequest.service_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='virtual_endpoint.ServiceRequest.request', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=222,
)


_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='virtual_endpoint.ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='virtual_endpoint.ServiceResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=259,
)

DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['TopicMessage'] = _TOPICMESSAGE
DESCRIPTOR.message_types_by_name['ServiceRequest'] = _SERVICEREQUEST
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'virtual_endpoint.proto.ros_service_pb2'
  # @@protoc_insertion_point(class_scope:virtual_endpoint.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

TopicMessage = _reflection.GeneratedProtocolMessageType('TopicMessage', (_message.Message,), {
  'DESCRIPTOR' : _TOPICMESSAGE,
  '__module__' : 'virtual_endpoint.proto.ros_service_pb2'
  # @@protoc_insertion_point(class_scope:virtual_endpoint.TopicMessage)
  })
_sym_db.RegisterMessage(TopicMessage)

ServiceRequest = _reflection.GeneratedProtocolMessageType('ServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEREQUEST,
  '__module__' : 'virtual_endpoint.proto.ros_service_pb2'
  # @@protoc_insertion_point(class_scope:virtual_endpoint.ServiceRequest)
  })
_sym_db.RegisterMessage(ServiceRequest)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICERESPONSE,
  '__module__' : 'virtual_endpoint.proto.ros_service_pb2'
  # @@protoc_insertion_point(class_scope:virtual_endpoint.ServiceResponse)
  })
_sym_db.RegisterMessage(ServiceResponse)



_ROSNODE = _descriptor.ServiceDescriptor(
  name='RosNode',
  full_name='virtual_endpoint.RosNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=262,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='virtual_endpoint.RosNode.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_TOPICMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CallService',
    full_name='virtual_endpoint.RosNode.CallService',
    index=1,
    containing_service=None,
    input_type=_SERVICEREQUEST,
    output_type=_SERVICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROSNODE)

DESCRIPTOR.services_by_name['RosNode'] = _ROSNODE

# @@protoc_insertion_point(module_scope)
