# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from virtual_endpoint.proto import ros_service_pb2 as virtual__endpoint_dot_proto_dot_ros__service__pb2


class RosNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/virtual_endpoint.RosNode/Subscribe',
                request_serializer=virtual__endpoint_dot_proto_dot_ros__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=virtual__endpoint_dot_proto_dot_ros__service__pb2.TopicMessage.FromString,
                )


class RosNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RosNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=virtual__endpoint_dot_proto_dot_ros__service__pb2.SubscribeRequest.FromString,
                    response_serializer=virtual__endpoint_dot_proto_dot_ros__service__pb2.TopicMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virtual_endpoint.RosNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RosNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/virtual_endpoint.RosNode/Subscribe',
            virtual__endpoint_dot_proto_dot_ros__service__pb2.SubscribeRequest.SerializeToString,
            virtual__endpoint_dot_proto_dot_ros__service__pb2.TopicMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
