//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveActionFeedback : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveAction";

        //  feedback
        public double progress;

        public MoveActionFeedback()
        {
            this.progress = 0.0;
        }

        public MoveActionFeedback(double progress)
        {
            this.progress = progress;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.progress));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.progress = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "MoveActionFeedback: " +
            "\nprogress: " + progress.ToString();
        }
    }
}
