//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveActionGoal : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveAction";

        //  goal
        public MoveCommand cmd;

        public MoveActionGoal()
        {
            this.cmd = new MoveCommand();
        }

        public MoveActionGoal(MoveCommand cmd)
        {
            this.cmd = cmd;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(cmd.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.cmd.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MoveActionGoal: " +
            "\ncmd: " + cmd.ToString();
        }
    }
}
