//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveActionResult : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveAction";

        //  result
        public int result;

        public MoveActionResult()
        {
            this.result = 0;
        }

        public MoveActionResult(int result)
        {
            this.result = result;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.result));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.result = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MoveActionResult: " +
            "\nresult: " + result.ToString();
        }
    }
}
