version: '3.4'
#  docker 
#   run -it --rm -v 
#   $(pwd)/Frontend/public/workspaces/pole_cart_python:/python_ws/src 
#   -p 10000:10000 
#   -p 50051:50051 
#   -p 60061:60061 
#   -p 60062:60062 
#   robottycoon.azurecr.io/unity-robotics-pick-and-place 
#   ./src/start.sh

services:
  simulation:
    image: mcr.microsoft.com/windows:10.0.19041.867
    environment:
      DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
    #image: mcr.microsoft.com/windows/servercore:1903
    platform: windows  
    ports:
     - "3389:3389"
     - "80:80"
    volumes:
      - type: bind
        source: C:\Users\benja\Documents\robots\LATEST
        target: C:\Sim
    command: powershell -executionpolicy bypass "ls C:\Sim;cd C:\Sim\robot-tycoon\Docker\pick_and_place\docker; ls;./StreamingWrapper.ps1"
    extra_hosts:
      - "dockerhost: 192.168.96.1"
