version: '3.4'
#  docker 
#   run -it --rm -v 
#   $(pwd)/Frontend/public/workspaces/pole_cart_python:/python_ws/src 
#   -p 10000:10000 
#   -p 50051:50051 
#   -p 60061:60061 
#   -p 60062:60062 
#   robottycoon.azurecr.io/unity-robotics-pick-and-place 
#   ./src/start.sh
#
# host.docker.internal

services:
  ros-server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: docker_ros-server:latest
    #image: robottycoon.azurecr.io/unity-robotics-pick-and-place
    restart: always
    environment:
      - SAVED_MODELS_DIR=/saved_models
      - ROBOT_TYPE=robotaxi
      #- UNITY_MACHINE_IP=simulator commented out and should revert to standard behavior of pointing to localhost
      - UNITY_MACHINE_IP=host.docker.internal
    build:
      #from: robottycoon.azurecr.io/unity-robotics-pick-and-place 
      context:  C:\Users\benja\Documents\robots\LATEST\robot-tycoon\Docker\pick_and_place
      dockerfile: docker\Dockerfile
    volumes:  
      - type: bind
        source: C:\Users\benja\Documents\robots\LATEST\robot-tycoon\Frontend\public\workspaces\python 
        target: /python_ws/src
      - type: bind
        source: C:\Users\benja\Documents\robots\LATEST\saved_models 
        target: /saved_models
    ports:
      - "10000:10000" 
      - "50051:50051" 
      # - "60061:60061" 
      # - "60062:60062"
    command: sh -c "./src/start.sh"
    # links:
    #   - "simulator"
    #   - "sim-controller"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:  
      - type: bind
        source: C:\Users\benja\Documents\robots\LATEST\mongodb\
        target: /data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  # front-end:
  #   image: node:15.8
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - type: bind
  #       source: C:\Users\benja\Documents\robots\LATEST\robot-tycoon\Frontend
  #       target: /Frontend
  #   links:
  #     - "ros-server"
  #     # - "webapp"
  #   command: sh -c "cd /Frontend && npm start"
  sim-controller:
    image: sim_controller:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SAVED_MODELS_DIR=/saved_models
      - ROBOT_TYPE=robotaxi
    volumes:  
      - type: bind
        source: C:\Users\benja\Documents\robots\LATEST\robot-tycoon\Frontend\public\workspaces\python 
        target: /python_ws/src
      - type: bind
        source: C:\Users\benja\Documents\robots\LATEST\saved_models 
        target: /saved_models
    build:
      context:  C:\Users\benja\Documents\robots\LATEST\robot-tycoon\Docker\pick_and_place
      dockerfile: docker\Dockerfile
    ports:
      # - "5005:5005"
      - "6006:6006"
      # - "60061:60061" 
      # - "60062:60062"
    command: sh -c "(tensorboard --bind_all --logdir /tmp --reload_multifile true &1> /tmp/tb.log) && cd /python_ws/src && python robotaxi.py"
    links:
      # - "simulator"
      - "mongo"
  # simulator:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   image: racelinux:latest
  #   restart: always
  #   ports:
  #     - "5005:5005"
  #   links:
  #     - "ros-server"
      # - "webapp"
  # webapp:
  #   image: node:15.8
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - type: bind
  #       source: C:\Users\benja\Documents\robots\LATEST\robot-tycoon\WebApp
  #       target: /WebApp
  #   links:
  #     - "ros-server"
  #   command: sh -c "cd /WebApp && npm start"
  # simulation:
  #   image: mcr.microsoft.com/windows:10.0.19041.867
  #   environment:
  #     DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
  #   image: mcr.microsoft.com/windows/servercore:1903
  #   platform: windows  
  #   ports:
  #     - "1-79:1-79"
  #     - "81-2999:81-2999"
  #     - "3001-65535:3001-65535"
  #     - "49000-49500:49000-50000"
  #     - "135:135"
  #     - "53432:53432"
  #    - "3389:3389"
  #       - "80:80"
  #   volumes:
  #     - type: bind
  #       source: C:\Users\benja\Documents\robots\LATEST
  #       target: C:\Sim
  #   command: powershell -executionpolicy bypass "ls C:\Sim;cd C:\Sim; ls;./StreamingWrapper.ps1"
  #   extra_hosts:
  #     - "dockerhost: 192.168.96.1"
