# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fly_brain.proto import fly_brain_pb2 as fly__brain_dot_proto_dot_fly__brain__pb2


class FlyBrainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/fly_brain.FlyBrain/Info',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.InfoRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.InfoReply.FromString,
                )
        self.Reset = channel.unary_unary(
                '/fly_brain.FlyBrain/Reset',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.ResetRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.ResetReply.FromString,
                )
        self.Step = channel.unary_unary(
                '/fly_brain.FlyBrain/Step',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.StepRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.StepReply.FromString,
                )
        self.Snapshot = channel.unary_unary(
                '/fly_brain.FlyBrain/Snapshot',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.SnapshotReply.FromString,
                )
        self.Geometry = channel.unary_unary(
                '/fly_brain.FlyBrain/Geometry',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.GeometryRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.GeometryReply.FromString,
                )
        self.Cells = channel.unary_unary(
                '/fly_brain.FlyBrain/Cells',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.CellsRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.CellsReply.FromString,
                )
        self.Sectors = channel.unary_unary(
                '/fly_brain.FlyBrain/Sectors',
                request_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.SectorsRequest.SerializeToString,
                response_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.SectorsReply.FromString,
                )


class FlyBrainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Info(self, request, context):
        """Static facts: neuron/connection counts, device, dt, trace width.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Clear voltages and reseed. Call at every episode boundary: the brain is
        stateful, so a new episode must not inherit the previous one's voltages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Advance the brain `substeps` times under a fixed injection and return the
        decaying descending-neuron trace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Current overlay activity without advancing the brain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Geometry(self, request, context):
        """Static overlay geometry. Fetch once; it never changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cells(self, request, context):
        """Resolve cell types or a named group to neuron indices. The step-4 encoder
        needs these to aim its injections, and only this side can answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sectors(self, request, context):
        """Split a population into k spatial sectors for the retinotopic encoder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlyBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.InfoRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.InfoReply.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.ResetRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.ResetReply.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.StepRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.StepReply.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.SnapshotRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.SnapshotReply.SerializeToString,
            ),
            'Geometry': grpc.unary_unary_rpc_method_handler(
                    servicer.Geometry,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.GeometryRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.GeometryReply.SerializeToString,
            ),
            'Cells': grpc.unary_unary_rpc_method_handler(
                    servicer.Cells,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.CellsRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.CellsReply.SerializeToString,
            ),
            'Sectors': grpc.unary_unary_rpc_method_handler(
                    servicer.Sectors,
                    request_deserializer=fly__brain_dot_proto_dot_fly__brain__pb2.SectorsRequest.FromString,
                    response_serializer=fly__brain_dot_proto_dot_fly__brain__pb2.SectorsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fly_brain.FlyBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlyBrain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Info',
            fly__brain_dot_proto_dot_fly__brain__pb2.InfoRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.InfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Reset',
            fly__brain_dot_proto_dot_fly__brain__pb2.ResetRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.ResetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Step',
            fly__brain_dot_proto_dot_fly__brain__pb2.StepRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.StepReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Snapshot',
            fly__brain_dot_proto_dot_fly__brain__pb2.SnapshotRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.SnapshotReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Geometry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Geometry',
            fly__brain_dot_proto_dot_fly__brain__pb2.GeometryRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.GeometryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cells(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Cells',
            fly__brain_dot_proto_dot_fly__brain__pb2.CellsRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.CellsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fly_brain.FlyBrain/Sectors',
            fly__brain_dot_proto_dot_fly__brain__pb2.SectorsRequest.SerializeToString,
            fly__brain_dot_proto_dot_fly__brain__pb2.SectorsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
