# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros_node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ros_node.proto',
  package='ros',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eros_node.proto\x12\x03ros\"3\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08msg_type\x18\x02 \x01(\t\"\x1c\n\x0cTopicMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2B\n\x07RosNode\x12\x37\n\tSubscribe\x12\x15.ros.SubscribeRequest\x1a\x11.ros.TopicMessage0\x01\x62\x06proto3'
)




_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='ros.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='ros.SubscribeRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='ros.SubscribeRequest.msg_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=74,
)


_TOPICMESSAGE = _descriptor.Descriptor(
  name='TopicMessage',
  full_name='ros.TopicMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ros.TopicMessage.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['TopicMessage'] = _TOPICMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'ros_node_pb2'
  # @@protoc_insertion_point(class_scope:ros.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

TopicMessage = _reflection.GeneratedProtocolMessageType('TopicMessage', (_message.Message,), {
  'DESCRIPTOR' : _TOPICMESSAGE,
  '__module__' : 'ros_node_pb2'
  # @@protoc_insertion_point(class_scope:ros.TopicMessage)
  })
_sym_db.RegisterMessage(TopicMessage)



_ROSNODE = _descriptor.ServiceDescriptor(
  name='RosNode',
  full_name='ros.RosNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=106,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='ros.RosNode.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_TOPICMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROSNODE)

DESCRIPTOR.services_by_name['RosNode'] = _ROSNODE

# @@protoc_insertion_point(module_scope)
