//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveActionGoal : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveAction";

        //  goal
        public MoveCommand cmd;
        public int cmd_id;

        public MoveActionGoal()
        {
            this.cmd = new MoveCommand();
            this.cmd_id = 0;
        }

        public MoveActionGoal(MoveCommand cmd, int cmd_id)
        {
            this.cmd = cmd;
            this.cmd_id = cmd_id;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(cmd.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.cmd_id));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.cmd.Deserialize(data, offset);
            this.cmd_id = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MoveActionGoal: " +
            "\ncmd: " + cmd.ToString() +
            "\ncmd_id: " + cmd_id.ToString();
        }
    }
}
