//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class MoveActionFeedback : Message
    {
        public const string RosMessageName = "niryo_moveit/MoveAction";

        //  feedback
        public double progress;
        public int cmd_id;

        public MoveActionFeedback()
        {
            this.progress = 0.0;
            this.cmd_id = 0;
        }

        public MoveActionFeedback(double progress, int cmd_id)
        {
            this.progress = progress;
            this.cmd_id = cmd_id;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.progress));
            listOfSerializations.Add(BitConverter.GetBytes(this.cmd_id));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.progress = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.cmd_id = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "MoveActionFeedback: " +
            "\nprogress: " + progress.ToString() +
            "\ncmd_id: " + cmd_id.ToString();
        }
    }
}
