<#
.SYNOPSIS
    Clone an existing job document as a fresh NOT_STARTED job, optionally
    assigning a reward design and marking the source job DONE.

.DESCRIPTION
    Copies every config field of the source job (gym, experiment design,
    num_iterations, demo_job_ids, demo_source_counts, etc.) into a brand-new
    job document, then strips the identity / progress / lifecycle fields so
    the trainer treats the clone as a clean fresh-start run:

        _id, percent_complete, training_steps, started_at, ended_at,
        paused_at_step, watchdog_resume_count, trainer_git_sha,
        trainer_git_branch

    The clone is inserted with status='NOT_STARTED' and a new create_date, so
    the next trainer launch (or the sim-controller poll loop) picks it up and
    starts from step 0 with NO checkpoint resume (paused_at_step is absent).

    This is the reusable form of the ad-hoc mongosh scripts used to restart a
    stuck curriculum job from a clone. Typical flow:

        1. Kill the running trainer.
        2. .\scripts\Clone-Job.ps1 -SourceJobId <id> [-RewardDesignId <id>] -SetSourceDone
        3. Relaunch the trainer; it polls for the NOT_STARTED clone.

.PARAMETER SourceJobId
    24-char hex ObjectId of the job to clone.

.PARAMETER RewardDesignId
    Optional reward_designs ObjectId (as a string) to attach to the clone via
    the job-doc `reward_design_id` field. do_job resolves it with
    ObjectId(str(...)), so a plain hex string is correct. Omit to leave the
    clone with whatever reward design the source had (or none).

.PARAMETER RewardDesignName
    Optional human-readable name stored alongside on `reward_design_name`
    (cosmetic; the trainer resolves the design by id, not name).

.PARAMETER Notes
    Optional replacement for the clone's `notes` field. Omit to keep the
    source job's notes verbatim.

.PARAMETER SetSourceDone
    If set, marks the SOURCE job status='DONE' (with ended_at=now) before
    cloning. Use when you're retiring a stuck/finished run and replacing it
    with the clone.

.PARAMETER DryRun
    Print the generated mongosh script and exit without touching MongoDB.
    Useful to preview exactly what will be inserted / updated.

.PARAMETER MongoConn
    MongoDB connection string used inside the mongo container. Defaults to the
    stack's root credentials.

.EXAMPLE
    # Clone a job and attach the v4 goal-count-speed reward design, retiring the source.
    .\scripts\Clone-Job.ps1 -SourceJobId 6a6290d6c496c2efed601a04 `
        -RewardDesignId 6a3350e52ddfadd149b0db2f `
        -RewardDesignName 'Goal-count speed (v4, TIME_COST 0.0073)' `
        -SetSourceDone

.EXAMPLE
    # Plain clone (keep source running), no reward-design change.
    .\scripts\Clone-Job.ps1 -SourceJobId 6a6290d6c496c2efed601a04
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$SourceJobId,
    [string]$RewardDesignId,
    [string]$RewardDesignName,
    [string]$Notes,
    [switch]$SetSourceDone,
    [switch]$DryRun,
    [string]$MongoConn = 'mongodb://root:example@localhost:27017/robotaxi?authSource=admin'
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent

# Encode string params as JS literals (or the JS keyword `null` when unset) so
# the generated script is injection-safe even for notes containing quotes.
function ConvertTo-JsLiteral($value) {
    if ([string]::IsNullOrEmpty($value)) { return 'null' }
    return ($value | ConvertTo-Json -Compress)
}

$srcJs      = ($SourceJobId | ConvertTo-Json -Compress)
$rdIdJs     = ConvertTo-JsLiteral $RewardDesignId
$rdNameJs   = ConvertTo-JsLiteral $RewardDesignName
$notesJs    = ConvertTo-JsLiteral $Notes
$setDoneJs  = if ($SetSourceDone) { 'true' } else { 'false' }

$js = @"
// Auto-generated by scripts/Clone-Job.ps1 - safe to delete.
const srcId = ObjectId($srcJs);
const REWARD_DESIGN_ID   = $rdIdJs;
const REWARD_DESIGN_NAME = $rdNameJs;
const NOTES              = $notesJs;
const SET_SOURCE_DONE    = $setDoneJs;

if (SET_SOURCE_DONE) {
  const doneRes = db.jobs.updateOne(
    { _id: srcId },
    { `$set: { status: 'DONE', ended_at: new Date().toISOString() } });
  print('Source ' + srcId + ' -> DONE: ' + JSON.stringify(doneRes));
}

const src = db.jobs.findOne({ _id: srcId });
if (!src) { throw new Error('source job not found: ' + srcId); }

const clone = Object.assign({}, src);
['_id', 'percent_complete', 'training_steps', 'started_at', 'ended_at',
 'paused_at_step', 'watchdog_resume_count', 'trainer_git_sha',
 'trainer_git_branch'].forEach(function (k) { delete clone[k]; });

clone.status = 'NOT_STARTED';
clone.create_date = new Date().toISOString();
if (REWARD_DESIGN_ID   !== null) { clone.reward_design_id   = REWARD_DESIGN_ID; }
if (REWARD_DESIGN_NAME !== null) { clone.reward_design_name = REWARD_DESIGN_NAME; }
if (NOTES              !== null) { clone.notes              = NOTES; }

const ins = db.jobs.insertOne(clone);
print('Clone inserted _id: ' + ins.insertedId);
printjson(db.jobs.findOne({ _id: ins.insertedId }, {
  status: 1, job_type: 1, gym_name: 1, num_iterations: 1,
  experiment_design_id: 1, reward_design_id: 1, reward_design_name: 1,
  demo_job_ids: 1, demo_source_counts: 1, percent_complete: 1,
  training_steps: 1, paused_at_step: 1 }));
"@

if ($DryRun) {
    Write-Host "=== DryRun: generated mongosh script (not executed) ===" -ForegroundColor Yellow
    Write-Host $js
    return
}

$localTmp = Join-Path $env:TEMP ("clone-job-" + [guid]::NewGuid().ToString('N') + ".js")
$containerTmp = "/tmp/_clone_job.js"
Set-Content -LiteralPath $localTmp -Value $js -Encoding UTF8

Push-Location $repoRoot
try {
    Write-Host "Cloning job $SourceJobId ..."
    docker compose cp $localTmp ("mongo:" + $containerTmp)
    if ($LASTEXITCODE -ne 0) { throw "docker compose cp failed ($LASTEXITCODE)" }

    docker compose exec -T mongo mongosh $MongoConn --quiet --file $containerTmp
    if ($LASTEXITCODE -ne 0) { throw "mongosh clone script failed ($LASTEXITCODE)" }
} finally {
    Pop-Location
    Remove-Item -LiteralPath $localTmp -ErrorAction SilentlyContinue
}
